sudo: required
language: java
jdk: oraclejdk8

services:
  - docker
  - mysql

before_install:
  - docker run -e MYSQL_ROOT_PASSWORD=petclinic -e MYSQL_DATABASE=petclinic -p 3306:3306 mysql:5.7.8

after_success:
  - bash <(curl -s https://codecov.io/bash)
